steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
    - "build"
    - "-t"
    - "${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dga-dataproc-base:$SHORT_SHA"
    - "-t"
    - "${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dga-dataproc-base:latest"
    - "-f"
    - "Dockerfile.base"
    - "."
    id: "Build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dga-dataproc-base", "--all-tags"]

substitutions:
  _LOCATION: us-west3
  _IMAGE_PROJECT_ID: dga-athena-sandbox
  _REPOSITORY: dataproc-images
