steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "dataproc-pipeline-test-container", "-f", "Dockerfile.unittest", ".", "--build-arg", "BASE_IMAGE=${_BASE_IMAGE}"]
    timeout: 9000s

  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "dataproc-pipeline-test-container", "pytest", "-n", "2", "-vv", "/packages/dataproc_package/"]
    timeout: 9000s
timeout: 9000s

substitutions:
  _LOCATION: us-central1
  _IMAGE_PROJECT_ID: asu-ap-gap-test-2360
  _REPOSITORY: dataproc-images
  _BASE_IMAGE: ${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dataproc-base:latest

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
