steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
    - "build"
    - "-t"
    - "${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dataproc-base:$SHORT_SHA"
    - "-t"
    - "${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dataproc-base:latest"
    - "-f"
    - "Dockerfile.base"
    - "."
    id: "Build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_LOCATION}-docker.pkg.dev/${_IMAGE_PROJECT_ID}/${_REPOSITORY}/dataproc-base", "--all-tags"]

substitutions:
  _LOCATION: us-central1
  _IMAGE_PROJECT_ID: br-sbx-app-0
  _REPOSITORY: ushe-dataproc-test

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
